# Generated by Django 4.2.23 on 2025-08-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GazonBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='gazon_brand/')),
            ],
        ),
        migrations.CreateModel(
            name='GilamBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='gilam_brand/')),
            ],
        ),
        migrations.CreateModel(
            name='KovrolinBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='kovrolin_brand/')),
            ],
        ),
        migrations.CreateModel(
            name='MetrliYolakBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='metrliyolak_brand/')),
            ],
        ),
        migrations.CreateModel(
            name='MetrliYolakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yolak_mark', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='metrliyolak_model/')),
                ('room', models.CharField(choices=[('mexmonxona', 'Mexmonxona'), ('yotoqxona', 'Yotoqxona'), ('oshxona', 'Oshxona'), ('bolalar_xonasi', 'Bolalar xonasi')], max_length=50)),
                ('color', models.CharField(choices=[('qizil', 'Qizil'), ('oq', 'Oq'), ('kok', 'Ko`k'), ('jigar', 'Jigar'), ('qora', 'Qora')], max_length=50)),
                ('size', models.CharField(choices=[('tortburchak', 'To`rtburchak'), ('oval', 'Oval')], max_length=50)),
                ('price', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('xit', 'Xit'), ('yangilik', 'Yangilik'), ('chegirma', 'Chegirma'), ('kop_sotilgan', 'Ko‘p sotilgan')], default='yangilik', max_length=50)),
                ('yolak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Catalog.metrliyolakbrand')),
            ],
        ),
        migrations.CreateModel(
            name='KovrolinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kovrolin_mark', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='kovrolin_model/')),
                ('room', models.CharField(choices=[('mexmonxona', 'Mexmonxona'), ('yotoqxona', 'Yotoqxona'), ('oshxona', 'Oshxona'), ('bolalar_xonasi', 'Bolalar xonasi')], max_length=50)),
                ('color', models.CharField(choices=[('qizil', 'Qizil'), ('oq', 'Oq'), ('kok', 'Ko`k'), ('jigar', 'Jigar'), ('qora', 'Qora')], max_length=50)),
                ('size', models.CharField(choices=[('tortburchak', 'To`rtburchak'), ('oval', 'Oval')], max_length=50)),
                ('price', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('xit', 'Xit'), ('yangilik', 'Yangilik'), ('chegirma', 'Chegirma'), ('kop_sotilgan', 'Ko‘p sotilgan')], default='yangilik', max_length=50)),
                ('kovrolin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Catalog.kovrolinbrand')),
            ],
        ),
        migrations.CreateModel(
            name='GilamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gilam_mark', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='gilam_model/')),
                ('room', models.CharField(choices=[('mexmonxona', 'Mexmonxona'), ('yotoqxona', 'Yotoqxona'), ('oshxona', 'Oshxona'), ('bolalar_xonasi', 'Bolalar xonasi')], max_length=50)),
                ('color', models.CharField(choices=[('qizil', 'Qizil'), ('oq', 'Oq'), ('kok', 'Ko`k'), ('jigar', 'Jigar'), ('qora', 'Qora')], max_length=50)),
                ('size', models.CharField(choices=[('tortburchak', 'To`rtburchak'), ('oval', 'Oval')], max_length=50)),
                ('style', models.CharField(choices=[('klassik', 'Klassik dizayn'), ('neoklassik', 'Neoklassik'), ('zamonaviy', 'Zamonaviy dizayn'), ('bolalar', 'Bolalar dizayn')], max_length=50)),
                ('price', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('xit', 'Xit'), ('yangilik', 'Yangilik'), ('chegirma', 'Chegirma'), ('kop_sotilgan', 'Ko‘p sotilgan')], default='yangilik', max_length=50)),
                ('gilam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Catalog.gilambrand')),
            ],
        ),
        migrations.CreateModel(
            name='GazonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazon_mark', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='gazon_model/')),
                ('room', models.CharField(choices=[('mexmonxona', 'Mexmonxona'), ('yotoqxona', 'Yotoqxona'), ('oshxona', 'Oshxona'), ('bolalar_xonasi', 'Bolalar xonasi')], max_length=50)),
                ('color', models.CharField(choices=[('qizil', 'Qizil'), ('oq', 'Oq'), ('kok', 'Ko`k'), ('jigar', 'Jigar'), ('qora', 'Qora')], max_length=50)),
                ('size', models.CharField(choices=[('tortburchak', 'To`rtburchak'), ('oval', 'Oval')], max_length=50)),
                ('price', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('xit', 'Xit'), ('yangilik', 'Yangilik'), ('chegirma', 'Chegirma'), ('kop_sotilgan', 'Ko‘p sotilgan')], default='yangilik', max_length=50)),
                ('gazon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Catalog.gazonbrand')),
            ],
        ),
    ]
